---
# title: DTC Persona Pipeline
config:
    theme: dark
    layout: elk
---
graph TD
    subgraph "Local Machine"
        A[TERRAFORM script]
        H[prediction request script]
    end

    subgraph "Google Cloud Platform"
        B[GCS bucket]
    end

        subgraph "<div style='text-align: center;'>TELEGRAM<br/>messenger service</div>"
        L["<div style='text-align: left;'>chat notification<br/>"]
    end

    subgraph "Docker Compose Stack"
        C["<div style='text-align: left;'>PostgreSQL database<br/>  - model registry<br/>  - customer database</div>"]
        
        subgraph E [MAGE Pipeline]
            
            J[Transform] 
            --> 
            K["<div style='text-align: left;'>EVIDENTLY<br/>  - monitoring</div>"]
            --"if data drift"--> 
            D["<div style='text-align: left;'>MLFLOW tracking server<br/>  - model retraining<br/>  - return best run</div>"]
        end
        F[CloudBeaver UI]
    end

    subgraph "Docker Container"
        G[GUNICORN web service]
    end

    I(("<div style='text-align: center;'>predicted<br/>labels</div>"))

    A -->|"provides"| B
    
    D --"artifacts"--> B
    D --"register model and<br/>promote to production"--> C
    
    F --"client access"--> C
    C --"new customer data<br/>reference customer data"--> J

    H ----> G
    C --"production model"--> G

    G --"runs k-means model"--> I

    K --> L
    K ~~~ L