---
# DTC Persona Pipeline
config:
    theme: dark
    layout: elk
---
graph TD
    %% Main infrastructure blocks
    subgraph "Local Machine"
        A[TERRAFORM script]
        H[parameterized <br> batch prediction script]
    end

    subgraph "Google Cloud Platform"
        B[GCS bucket for artifacts]
    end

    subgraph "Docker Compose Stack"
        C["PostgreSQL<br/>• model registry<br/>• customer database"]
        F[CloudBeaver UI]
        
        subgraph "MAGE Pipeline"
            J[Transform] --> K["EVIDENTLY<br/>• monitoring"]
            D["MLFLOW Tracking Server<br/>• manages model lifecycle"]
        end

    end
    
    subgraph "GUNICORN"
        G[GUNICORN web service]
    end 
    
    subgraph "External Service"
        L["TELEGRAM<br/>• drift notifications
                        • retraining notifications"]
    end

    %% Outputs
    I(("<div style='text-align: center;'>predicted<br/>persona labels</div>"))


    %% Connections
    
    %% --- Infrastructure & Model Management Flow ---
    A --"provisions<br>cloud storage"--> B
    F --"db client access"--> C
    C --"reads customer data"--> J
    K --"if data drift"--> D
    D --"retrains & logs artifacts"--> B
    D --"registers best model"--> C
    D~~~C
    K --"sends alert"--> L


    %% --- Batch Prediction Flow (Deduplicated) ---
    D -- "loads production model" --> G
    H -- "queries new data from db" --> C
    C -- "provides data" --> G
    G -- "runs prediction" --> I
    I -- "ingestion<br>add labels to new data" --> C