version: 0.1.1
default:
  # Default profile created for data IO access.
  # When using a local filesystem, you can leave these empty
  MAGE_ACCESS_KEY: ''
  MAGE_SECRET_ACCESS_KEY: ''

  # This is the key setting for local files!
  # 'default_repo' is a special keyword that tells Mage to use
  # the root directory of your project as the data directory.
  MAGE_DATA_DIR: 'default_repo'

  
  # # PostgresSQL
  # # POSTGRES_CONNECT_TIMEOUT: 10
  # # POSTGRES_DBNAME: mydb
  # # POSTGRES_SCHEMA: public # Optional
  # # POSTGRES_USER: user
  # # POSTGRES_PASSWORD: password
  # # POSTGRES_HOST: postgres
  # # POSTGRES_PORT: 5432
  

dev_docker_postgres:
  type: postgres
  POSTGRES_USER: "{{ env_var('POSTGRES_USER') }}"
  POSTGRES_PASSWORD: "{{ env_var('POSTGRES_PASSWORD') }}"
  POSTGRES_HOST: "{{ env_var('POSTGRES_HOST') }}"
  POSTGRES_PORT: "{{ env_var('POSTGRES_PORT') }}"
  POSTGRES_DBNAME: "{{ env_var('POSTGRES_DBNAME') }}"
  POSTGRES_CONNECTION_METHOD: direct
  user: "{{ env_var('POSTGRES_USER') }}"
  password: "{{ env_var('POSTGRES_PASSWORD') }}"
  host: "{{ env_var('POSTGRES_HOST') }}"
  port: "{{ env_var('POSTGRES_PORT') }}"
  dbname: "{{ env_var('POSTGRES_DBNAME') }}"
  