version: '3.8'
name: dtc_persona_monitoring
services:
  dbeaver:
    image: dbeaver/cloudbeaver:latest
    container_name: dbeaver
    ports:
      - "8978:8978"
    environment:
      - CB_SERVER_NAME=DBeaver
    volumes:
      - dbeaver_data:/opt/cloudbeaver/workspace
    restart: unless-stopped

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "4321:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
  dbeaver_data: